import sharp from 'sharp';
import { readdirSync } from 'node:fs';
import { writeFileSync } from 'node:fs';
const files = readdirSync('public').filter(f => f.endsWith('.webp')).sort();
const out = {};
for (const f of files) {
  const img = sharp('public/' + f);
  const { width, height } = await img.metadata();
  const buf = await img.resize(16, null, { fit: 'inside' }).webp({ quality: 40 }).toBuffer();
  out['/' + f] = { w: width, h: height, blur: 'data:image/webp;base64,' + buf.toString('base64') };
}
const body = Object.entries(out).map(([k,v]) => `  '${k}': { w: ${v.w}, h: ${v.h}, blur: '${v.blur}' },`).join('\n');
writeFileSync('src/lib/cover-meta.js', `/**
 * Intrinsic size and a 16px blur placeholder for every cover in public/.
 * Generated by scripts/cover-meta.mjs — rerun after adding or replacing a cover.
 */
export const COVER_META = {
${body}
};

export const coverMeta = (src) => COVER_META[src] ?? { w: 1920, h: 1000, blur: undefined };
`);
console.log('covers:', files.length, '| bytes:', body.length);
